baseurl = "https://thottingal.in/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Santhosh Thottingal"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "thottingal-in"
#googleAnalytics = "XXX"

[Params]
  #subtitle = "Thoughts of Thottingal"
  logo = "sa.png"
  favicon = "sa.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Santhosh Thottingal"
  email = "santhosh.thottingal@gmail.com"
  #facebook = "username"
  #googleplus = "+username" # or xxxxxxxxxxxxxxxxxxxxx
  gitlab = "santhoshtr"
  github = "santhoshtr"
  twitter = "santhoshtr"
  #reddit = "username"
  #linkedin = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #keybase = "username"

[taxonomies]
  category = "categories"
  tag = "tags"

[[menu.main]]
    name = "Blog"
    url = "blog"
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    url = "page/projects"
    name = "Projects"
    weight = 2

[[menu.main]]
    url = "page/talks"
    name = "Talks"
    weight = 2

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3
